# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wavedata_view.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WaveDataDialog(object):
    def setupUi(self, WaveDataDialog):
        WaveDataDialog.setObjectName("WaveDataDialog")
        WaveDataDialog.resize(400, 649)
        self.verticalLayout = QtWidgets.QVBoxLayout(WaveDataDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filePathLabel = QtWidgets.QLabel(WaveDataDialog)
        self.filePathLabel.setText("")
        self.filePathLabel.setObjectName("filePathLabel")
        self.verticalLayout.addWidget(self.filePathLabel)
        self.txtLabel = QtWidgets.QLabel(WaveDataDialog)
        self.txtLabel.setText("")
        self.txtLabel.setObjectName("txtLabel")
        self.verticalLayout.addWidget(self.txtLabel)
        self.latLabel = QtWidgets.QLabel(WaveDataDialog)
        self.latLabel.setText("")
        self.latLabel.setObjectName("latLabel")
        self.verticalLayout.addWidget(self.latLabel)
        self.lonLabel = QtWidgets.QLabel(WaveDataDialog)
        self.lonLabel.setText("")
        self.lonLabel.setObjectName("lonLabel")
        self.verticalLayout.addWidget(self.lonLabel)
        self.tabWidget = QtWidgets.QTabWidget(WaveDataDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.TextTab = QtWidgets.QWidget()
        self.TextTab.setObjectName("TextTab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.TextTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 371, 351))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.TextTab, "")
        self.wtsTab = QtWidgets.QWidget()
        self.wtsTab.setObjectName("wtsTab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.wtsTab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 351, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.wtsTableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.wtsTableWidget.setObjectName("wtsTableWidget")
        self.wtsTableWidget.setColumnCount(0)
        self.wtsTableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.wtsTableWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.wtsTab, "")
        self.wb0Tab = QtWidgets.QWidget()
        self.wb0Tab.setObjectName("wb0Tab")
        self.wb0TableWidget = QtWidgets.QTableWidget(self.wb0Tab)
        self.wb0TableWidget.setGeometry(QtCore.QRect(10, 10, 351, 331))
        self.wb0TableWidget.setObjectName("wb0TableWidget")
        self.wb0TableWidget.setColumnCount(0)
        self.wb0TableWidget.setRowCount(0)
        self.tabWidget.addTab(self.wb0Tab, "")
        self.wb1Tab = QtWidgets.QWidget()
        self.wb1Tab.setObjectName("wb1Tab")
        self.wb1TableWidget = QtWidgets.QTableWidget(self.wb1Tab)
        self.wb1TableWidget.setGeometry(QtCore.QRect(10, 20, 351, 331))
        self.wb1TableWidget.setObjectName("wb1TableWidget")
        self.wb1TableWidget.setColumnCount(0)
        self.wb1TableWidget.setRowCount(0)
        self.tabWidget.addTab(self.wb1Tab, "")
        self.wb2Tab = QtWidgets.QWidget()
        self.wb2Tab.setObjectName("wb2Tab")
        self.wb2TableWidget = QtWidgets.QTableWidget(self.wb2Tab)
        self.wb2TableWidget.setGeometry(QtCore.QRect(10, 10, 361, 331))
        self.wb2TableWidget.setObjectName("wb2TableWidget")
        self.wb2TableWidget.setColumnCount(0)
        self.wb2TableWidget.setRowCount(0)
        self.tabWidget.addTab(self.wb2Tab, "")
        self.wb3Tab = QtWidgets.QWidget()
        self.wb3Tab.setObjectName("wb3Tab")
        self.wb3TableWidget = QtWidgets.QTableWidget(self.wb3Tab)
        self.wb3TableWidget.setGeometry(QtCore.QRect(10, 10, 351, 331))
        self.wb3TableWidget.setObjectName("wb3TableWidget")
        self.wb3TableWidget.setColumnCount(0)
        self.wb3TableWidget.setRowCount(0)
        self.tabWidget.addTab(self.wb3Tab, "")
        self.wusTab = QtWidgets.QWidget()
        self.wusTab.setObjectName("wusTab")
        self.wusTableWidget = QtWidgets.QTableWidget(self.wusTab)
        self.wusTableWidget.setGeometry(QtCore.QRect(10, 10, 351, 331))
        self.wusTableWidget.setObjectName("wusTableWidget")
        self.wusTableWidget.setColumnCount(0)
        self.wusTableWidget.setRowCount(0)
        self.tabWidget.addTab(self.wusTab, "")
        self.wvsTab = QtWidgets.QWidget()
        self.wvsTab.setObjectName("wvsTab")
        self.wvsTableWidget = QtWidgets.QTableWidget(self.wvsTab)
        self.wvsTableWidget.setGeometry(QtCore.QRect(10, 10, 351, 331))
        self.wvsTableWidget.setObjectName("wvsTableWidget")
        self.wvsTableWidget.setColumnCount(0)
        self.wvsTableWidget.setRowCount(0)
        self.tabWidget.addTab(self.wvsTab, "")
        self.wzsTab = QtWidgets.QWidget()
        self.wzsTab.setObjectName("wzsTab")
        self.wzsTableWidget = QtWidgets.QTableWidget(self.wzsTab)
        self.wzsTableWidget.setGeometry(QtCore.QRect(10, 10, 351, 331))
        self.wzsTableWidget.setObjectName("wzsTableWidget")
        self.wzsTableWidget.setColumnCount(0)
        self.wzsTableWidget.setRowCount(0)
        self.tabWidget.addTab(self.wzsTab, "")
        self.wr0Tab = QtWidgets.QWidget()
        self.wr0Tab.setObjectName("wr0Tab")
        self.wr0TableWidget = QtWidgets.QTableWidget(self.wr0Tab)
        self.wr0TableWidget.setGeometry(QtCore.QRect(10, 20, 351, 321))
        self.wr0TableWidget.setObjectName("wr0TableWidget")
        self.wr0TableWidget.setColumnCount(0)
        self.wr0TableWidget.setRowCount(0)
        self.tabWidget.addTab(self.wr0Tab, "")
        self.wr1Tab = QtWidgets.QWidget()
        self.wr1Tab.setObjectName("wr1Tab")
        self.wr1TableWidget = QtWidgets.QTableWidget(self.wr1Tab)
        self.wr1TableWidget.setGeometry(QtCore.QRect(10, 10, 351, 331))
        self.wr1TableWidget.setObjectName("wr1TableWidget")
        self.wr1TableWidget.setColumnCount(0)
        self.wr1TableWidget.setRowCount(0)
        self.tabWidget.addTab(self.wr1Tab, "")
        self.wr2Tab = QtWidgets.QWidget()
        self.wr2Tab.setObjectName("wr2Tab")
        self.wr2TableWidget = QtWidgets.QTableWidget(self.wr2Tab)
        self.wr2TableWidget.setGeometry(QtCore.QRect(10, 10, 351, 331))
        self.wr2TableWidget.setObjectName("wr2TableWidget")
        self.wr2TableWidget.setColumnCount(0)
        self.wr2TableWidget.setRowCount(0)
        self.tabWidget.addTab(self.wr2Tab, "")
        self.wr3Tab = QtWidgets.QWidget()
        self.wr3Tab.setObjectName("wr3Tab")
        self.wr3TableWidget = QtWidgets.QTableWidget(self.wr3Tab)
        self.wr3TableWidget.setGeometry(QtCore.QRect(10, 10, 351, 331))
        self.wr3TableWidget.setObjectName("wr3TableWidget")
        self.wr3TableWidget.setColumnCount(0)
        self.wr3TableWidget.setRowCount(0)
        self.tabWidget.addTab(self.wr3Tab, "")
        self.wz0Tab = QtWidgets.QWidget()
        self.wz0Tab.setObjectName("wz0Tab")
        self.wz0TableWidget = QtWidgets.QTableWidget(self.wz0Tab)
        self.wz0TableWidget.setGeometry(QtCore.QRect(20, 20, 341, 321))
        self.wz0TableWidget.setObjectName("wz0TableWidget")
        self.wz0TableWidget.setColumnCount(0)
        self.wz0TableWidget.setRowCount(0)
        self.tabWidget.addTab(self.wz0Tab, "")
        self.wftTab = QtWidgets.QWidget()
        self.wftTab.setObjectName("wftTab")
        self.wftTableWidget = QtWidgets.QTableWidget(self.wftTab)
        self.wftTableWidget.setGeometry(QtCore.QRect(20, 20, 341, 321))
        self.wftTableWidget.setObjectName("wftTableWidget")
        self.wftTableWidget.setColumnCount(0)
        self.wftTableWidget.setRowCount(0)
        self.tabWidget.addTab(self.wftTab, "")
        self.whrTab = QtWidgets.QWidget()
        self.whrTab.setObjectName("whrTab")
        self.whrTableWidget = QtWidgets.QTableWidget(self.whrTab)
        self.whrTableWidget.setGeometry(QtCore.QRect(10, 10, 341, 321))
        self.whrTableWidget.setObjectName("whrTableWidget")
        self.whrTableWidget.setColumnCount(0)
        self.whrTableWidget.setRowCount(0)
        self.tabWidget.addTab(self.whrTab, "")
        self.wzrTab = QtWidgets.QWidget()
        self.wzrTab.setObjectName("wzrTab")
        self.wzrTableWidget = QtWidgets.QTableWidget(self.wzrTab)
        self.wzrTableWidget.setGeometry(QtCore.QRect(10, 20, 351, 321))
        self.wzrTableWidget.setObjectName("wzrTableWidget")
        self.wzrTableWidget.setColumnCount(0)
        self.wzrTableWidget.setRowCount(0)
        self.tabWidget.addTab(self.wzrTab, "")
        self.wahTab = QtWidgets.QWidget()
        self.wahTab.setObjectName("wahTab")
        self.wahTableWidget = QtWidgets.QTableWidget(self.wahTab)
        self.wahTableWidget.setGeometry(QtCore.QRect(10, 20, 351, 321))
        self.wahTableWidget.setObjectName("wahTableWidget")
        self.wahTableWidget.setColumnCount(0)
        self.wahTableWidget.setRowCount(0)
        self.tabWidget.addTab(self.wahTab, "")
        self.whsTab = QtWidgets.QWidget()
        self.whsTab.setObjectName("whsTab")
        self.whsTableWidget = QtWidgets.QTableWidget(self.whsTab)
        self.whsTableWidget.setGeometry(QtCore.QRect(10, 10, 351, 331))
        self.whsTableWidget.setObjectName("whsTableWidget")
        self.whsTableWidget.setColumnCount(0)
        self.whsTableWidget.setRowCount(0)
        self.tabWidget.addTab(self.whsTab, "")
        self.whpTab = QtWidgets.QWidget()
        self.whpTab.setObjectName("whpTab")
        self.whpTableWidget = QtWidgets.QTableWidget(self.whpTab)
        self.whpTableWidget.setGeometry(QtCore.QRect(10, 10, 351, 331))
        self.whpTableWidget.setObjectName("whpTableWidget")
        self.whpTableWidget.setColumnCount(0)
        self.whpTableWidget.setRowCount(0)
        self.tabWidget.addTab(self.whpTab, "")
        self.whgTab = QtWidgets.QWidget()
        self.whgTab.setObjectName("whgTab")
        self.whgTableWidget = QtWidgets.QTableWidget(self.whgTab)
        self.whgTableWidget.setGeometry(QtCore.QRect(10, 10, 351, 331))
        self.whgTableWidget.setObjectName("whgTableWidget")
        self.whgTableWidget.setColumnCount(0)
        self.whgTableWidget.setRowCount(0)
        self.tabWidget.addTab(self.whgTab, "")
        self.wphTab = QtWidgets.QWidget()
        self.wphTab.setObjectName("wphTab")
        self.wphTableWidget = QtWidgets.QTableWidget(self.wphTab)
        self.wphTableWidget.setGeometry(QtCore.QRect(20, 10, 341, 331))
        self.wphTableWidget.setObjectName("wphTableWidget")
        self.wphTableWidget.setColumnCount(0)
        self.wphTableWidget.setRowCount(0)
        self.tabWidget.addTab(self.wphTab, "")
        self.wdtTab = QtWidgets.QWidget()
        self.wdtTab.setObjectName("wdtTab")
        self.wdtTableWidget = QtWidgets.QTableWidget(self.wdtTab)
        self.wdtTableWidget.setGeometry(QtCore.QRect(10, 20, 351, 321))
        self.wdtTableWidget.setObjectName("wdtTableWidget")
        self.wdtTableWidget.setColumnCount(0)
        self.wdtTableWidget.setRowCount(0)
        self.tabWidget.addTab(self.wdtTab, "")
        self.wzpTab = QtWidgets.QWidget()
        self.wzpTab.setObjectName("wzpTab")
        self.wzpTableWidget = QtWidgets.QTableWidget(self.wzpTab)
        self.wzpTableWidget.setGeometry(QtCore.QRect(10, 10, 351, 331))
        self.wzpTableWidget.setObjectName("wzpTableWidget")
        self.wzpTableWidget.setColumnCount(0)
        self.wzpTableWidget.setRowCount(0)
        self.tabWidget.addTab(self.wzpTab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(WaveDataDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WaveDataDialog)

    def retranslateUi(self, WaveDataDialog):
        _translate = QtCore.QCoreApplication.translate
        WaveDataDialog.setWindowTitle(_translate("WaveDataDialog", "Dialog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TextTab), _translate("WaveDataDialog", "Text"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wtsTab), _translate("WaveDataDialog", "wts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wb0Tab), _translate("WaveDataDialog", "wb0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wb1Tab), _translate("WaveDataDialog", "wb1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wb2Tab), _translate("WaveDataDialog", "wb2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wb3Tab), _translate("WaveDataDialog", "wb3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wusTab), _translate("WaveDataDialog", "wus"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wvsTab), _translate("WaveDataDialog", "wvs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wzsTab), _translate("WaveDataDialog", "wzs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wr0Tab), _translate("WaveDataDialog", "wr0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wr1Tab), _translate("WaveDataDialog", "wr1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wr2Tab), _translate("WaveDataDialog", "wr2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wr3Tab), _translate("WaveDataDialog", "wr3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wz0Tab), _translate("WaveDataDialog", "wz0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wftTab), _translate("WaveDataDialog", "wft"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.whrTab), _translate("WaveDataDialog", "whr"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wzrTab), _translate("WaveDataDialog", "wzr"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wahTab), _translate("WaveDataDialog", "wah"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.whsTab), _translate("WaveDataDialog", "whs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.whpTab), _translate("WaveDataDialog", "whp"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.whgTab), _translate("WaveDataDialog", "whg"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wphTab), _translate("WaveDataDialog", "wph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wdtTab), _translate("WaveDataDialog", "wdt"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wzpTab), _translate("WaveDataDialog", "wzp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WaveDataDialog = QtWidgets.QDialog()
    ui = Ui_WaveDataDialog()
    ui.setupUi(WaveDataDialog)
    WaveDataDialog.show()
    sys.exit(app.exec_())

