# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wavedata_view.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WaveDataDialog(object):
    def setupUi(self, WaveDataDialog):
        WaveDataDialog.setObjectName("WaveDataDialog")
        WaveDataDialog.resize(823, 876)
        self.verticalLayout = QtWidgets.QVBoxLayout(WaveDataDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.filePathLabel = QtWidgets.QLabel(WaveDataDialog)
        self.filePathLabel.setText("")
        self.filePathLabel.setObjectName("filePathLabel")
        self.verticalLayout_18.addWidget(self.filePathLabel)
        self.txtLabel = QtWidgets.QLabel(WaveDataDialog)
        self.txtLabel.setText("")
        self.txtLabel.setObjectName("txtLabel")
        self.verticalLayout_18.addWidget(self.txtLabel)
        self.timeBetweenEnsembleLabel = QtWidgets.QLabel(WaveDataDialog)
        self.timeBetweenEnsembleLabel.setText("")
        self.timeBetweenEnsembleLabel.setObjectName("timeBetweenEnsembleLabel")
        self.verticalLayout_18.addWidget(self.timeBetweenEnsembleLabel)
        self.timeFirstEnsembleLabel = QtWidgets.QLabel(WaveDataDialog)
        self.timeFirstEnsembleLabel.setText("")
        self.timeFirstEnsembleLabel.setObjectName("timeFirstEnsembleLabel")
        self.verticalLayout_18.addWidget(self.timeFirstEnsembleLabel)
        self.latLabel = QtWidgets.QLabel(WaveDataDialog)
        self.latLabel.setText("")
        self.latLabel.setObjectName("latLabel")
        self.verticalLayout_18.addWidget(self.latLabel)
        self.lonLabel = QtWidgets.QLabel(WaveDataDialog)
        self.lonLabel.setText("")
        self.lonLabel.setObjectName("lonLabel")
        self.verticalLayout_18.addWidget(self.lonLabel)
        self.pressureSensorHeightLabel = QtWidgets.QLabel(WaveDataDialog)
        self.pressureSensorHeightLabel.setText("")
        self.pressureSensorHeightLabel.setObjectName("pressureSensorHeightLabel")
        self.verticalLayout_18.addWidget(self.pressureSensorHeightLabel)
        self.tabWidget = QtWidgets.QTabWidget(WaveDataDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.TextTab = QtWidgets.QWidget()
        self.TextTab.setObjectName("TextTab")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.TextTab)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.textBrowser = QtWidgets.QTextBrowser(self.TextTab)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_17.addWidget(self.textBrowser)
        self.tabWidget.addTab(self.TextTab, "")
        self.whvTab = QtWidgets.QWidget()
        self.whvTab.setObjectName("whvTab")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.whvTab)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.whvTab)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_12.addWidget(self.label_11)
        self.whvTableWidget = QtWidgets.QTableWidget(self.whvTab)
        self.whvTableWidget.setObjectName("whvTableWidget")
        self.whvTableWidget.setColumnCount(0)
        self.whvTableWidget.setRowCount(0)
        self.verticalLayout_12.addWidget(self.whvTableWidget)
        self.tabWidget.addTab(self.whvTab, "")
        self.wr0Tab = QtWidgets.QWidget()
        self.wr0Tab.setObjectName("wr0Tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.wr0Tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.wr0Tab)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.wr0TableWidget = QtWidgets.QTableWidget(self.wr0Tab)
        self.wr0TableWidget.setObjectName("wr0TableWidget")
        self.wr0TableWidget.setColumnCount(0)
        self.wr0TableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.wr0TableWidget)
        self.tabWidget.addTab(self.wr0Tab, "")
        self.wahTab = QtWidgets.QWidget()
        self.wahTab.setObjectName("wahTab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.wahTab)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.wahTab)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_11.addWidget(self.label_13)
        self.wahTableWidget = QtWidgets.QTableWidget(self.wahTab)
        self.wahTableWidget.setObjectName("wahTableWidget")
        self.wahTableWidget.setColumnCount(0)
        self.wahTableWidget.setRowCount(0)
        self.verticalLayout_11.addWidget(self.wahTableWidget)
        self.tabWidget.addTab(self.wahTab, "")
        self.whsTab = QtWidgets.QWidget()
        self.whsTab.setObjectName("whsTab")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.whsTab)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_17 = QtWidgets.QLabel(self.whsTab)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_20.addWidget(self.label_17)
        self.whsTableWidget = QtWidgets.QTableWidget(self.whsTab)
        self.whsTableWidget.setObjectName("whsTableWidget")
        self.whsTableWidget.setColumnCount(0)
        self.whsTableWidget.setRowCount(0)
        self.verticalLayout_20.addWidget(self.whsTableWidget)
        self.tabWidget.addTab(self.whsTab, "")
        self.wtsTab = QtWidgets.QWidget()
        self.wtsTab.setObjectName("wtsTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.wtsTab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.wtsTab)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.wtsTableWidget = QtWidgets.QTableWidget(self.wtsTab)
        self.wtsTableWidget.setObjectName("wtsTableWidget")
        self.wtsTableWidget.setColumnCount(0)
        self.wtsTableWidget.setRowCount(0)
        self.verticalLayout_7.addWidget(self.wtsTableWidget)
        self.tabWidget.addTab(self.wtsTab, "")
        self.wb0Tab = QtWidgets.QWidget()
        self.wb0Tab.setMaximumSize(QtCore.QSize(16777215, 680))
        self.wb0Tab.setObjectName("wb0Tab")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.wb0Tab)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_5 = QtWidgets.QLabel(self.wb0Tab)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_19.addWidget(self.label_5)
        self.wb0TableWidget = QtWidgets.QTableWidget(self.wb0Tab)
        self.wb0TableWidget.setObjectName("wb0TableWidget")
        self.wb0TableWidget.setColumnCount(0)
        self.wb0TableWidget.setRowCount(0)
        self.verticalLayout_19.addWidget(self.wb0TableWidget)
        self.tabWidget.addTab(self.wb0Tab, "")
        self.wb1Tab = QtWidgets.QWidget()
        self.wb1Tab.setObjectName("wb1Tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.wb1Tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.wb1Tab)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.wb1TableWidget = QtWidgets.QTableWidget(self.wb1Tab)
        self.wb1TableWidget.setObjectName("wb1TableWidget")
        self.wb1TableWidget.setColumnCount(0)
        self.wb1TableWidget.setRowCount(0)
        self.verticalLayout_6.addWidget(self.wb1TableWidget)
        self.tabWidget.addTab(self.wb1Tab, "")
        self.wb2Tab = QtWidgets.QWidget()
        self.wb2Tab.setObjectName("wb2Tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.wb2Tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.wb2Tab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.wb2TableWidget = QtWidgets.QTableWidget(self.wb2Tab)
        self.wb2TableWidget.setObjectName("wb2TableWidget")
        self.wb2TableWidget.setColumnCount(0)
        self.wb2TableWidget.setRowCount(0)
        self.verticalLayout_4.addWidget(self.wb2TableWidget)
        self.tabWidget.addTab(self.wb2Tab, "")
        self.wb3Tab = QtWidgets.QWidget()
        self.wb3Tab.setObjectName("wb3Tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.wb3Tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.wb3Tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.wb3TableWidget = QtWidgets.QTableWidget(self.wb3Tab)
        self.wb3TableWidget.setObjectName("wb3TableWidget")
        self.wb3TableWidget.setColumnCount(0)
        self.wb3TableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.wb3TableWidget)
        self.tabWidget.addTab(self.wb3Tab, "")
        self.wz0Tab = QtWidgets.QWidget()
        self.wz0Tab.setObjectName("wz0Tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.wz0Tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.wz0Tab)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.wz0TableWidget = QtWidgets.QTableWidget(self.wz0Tab)
        self.wz0TableWidget.setObjectName("wz0TableWidget")
        self.wz0TableWidget.setColumnCount(0)
        self.wz0TableWidget.setRowCount(0)
        self.verticalLayout_5.addWidget(self.wz0TableWidget)
        self.tabWidget.addTab(self.wz0Tab, "")
        self.wusTab = QtWidgets.QWidget()
        self.wusTab.setObjectName("wusTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.wusTab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.wusTab)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.wusTableWidget = QtWidgets.QTableWidget(self.wusTab)
        self.wusTableWidget.setObjectName("wusTableWidget")
        self.wusTableWidget.setColumnCount(0)
        self.wusTableWidget.setRowCount(0)
        self.verticalLayout_8.addWidget(self.wusTableWidget)
        self.tabWidget.addTab(self.wusTab, "")
        self.wvsTab = QtWidgets.QWidget()
        self.wvsTab.setObjectName("wvsTab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.wvsTab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.wvsTab)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.wvsTableWidget = QtWidgets.QTableWidget(self.wvsTab)
        self.wvsTableWidget.setObjectName("wvsTableWidget")
        self.wvsTableWidget.setColumnCount(0)
        self.wvsTableWidget.setRowCount(0)
        self.verticalLayout_9.addWidget(self.wvsTableWidget)
        self.tabWidget.addTab(self.wvsTab, "")
        self.wzsTab = QtWidgets.QWidget()
        self.wzsTab.setObjectName("wzsTab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.wzsTab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.wzsTab)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.wzsTableWidget = QtWidgets.QTableWidget(self.wzsTab)
        self.wzsTableWidget.setObjectName("wzsTableWidget")
        self.wzsTableWidget.setColumnCount(0)
        self.wzsTableWidget.setRowCount(0)
        self.verticalLayout_10.addWidget(self.wzsTableWidget)
        self.tabWidget.addTab(self.wzsTab, "")
        self.wpsTab = QtWidgets.QWidget()
        self.wpsTab.setObjectName("wpsTab")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.wpsTab)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.wpsTab)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_13.addWidget(self.label_12)
        self.wpsTableWidget = QtWidgets.QTableWidget(self.wpsTab)
        self.wpsTableWidget.setObjectName("wpsTableWidget")
        self.wpsTableWidget.setColumnCount(0)
        self.wpsTableWidget.setRowCount(0)
        self.verticalLayout_13.addWidget(self.wpsTableWidget)
        self.tabWidget.addTab(self.wpsTab, "")
        self.whgTab = QtWidgets.QWidget()
        self.whgTab.setObjectName("whgTab")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.whgTab)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.whgTab)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_14.addWidget(self.label_14)
        self.whgTableWidget = QtWidgets.QTableWidget(self.whgTab)
        self.whgTableWidget.setObjectName("whgTableWidget")
        self.whgTableWidget.setColumnCount(0)
        self.whgTableWidget.setRowCount(0)
        self.verticalLayout_14.addWidget(self.whgTableWidget)
        self.tabWidget.addTab(self.whgTab, "")
        self.wphTab = QtWidgets.QWidget()
        self.wphTab.setObjectName("wphTab")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.wphTab)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_16 = QtWidgets.QLabel(self.wphTab)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_15.addWidget(self.label_16)
        self.wphTableWidget = QtWidgets.QTableWidget(self.wphTab)
        self.wphTableWidget.setObjectName("wphTableWidget")
        self.wphTableWidget.setColumnCount(0)
        self.wphTableWidget.setRowCount(0)
        self.verticalLayout_15.addWidget(self.wphTableWidget)
        self.tabWidget.addTab(self.wphTab, "")
        self.wrlTab = QtWidgets.QWidget()
        self.wrlTab.setObjectName("wrlTab")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.wrlTab)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.wrlTab)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_16.addWidget(self.label_15)
        self.wrlTableWidget = QtWidgets.QTableWidget(self.wrlTab)
        self.wrlTableWidget.setObjectName("wrlTableWidget")
        self.wrlTableWidget.setColumnCount(0)
        self.wrlTableWidget.setRowCount(0)
        self.verticalLayout_16.addWidget(self.wrlTableWidget)
        self.tabWidget.addTab(self.wrlTab, "")
        self.verticalLayout_18.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.verticalLayout_18)

        self.retranslateUi(WaveDataDialog)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(WaveDataDialog)

    def retranslateUi(self, WaveDataDialog):
        _translate = QtCore.QCoreApplication.translate
        WaveDataDialog.setWindowTitle(_translate("WaveDataDialog", "Dialog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TextTab), _translate("WaveDataDialog", "Text"))
        self.label_11.setText(_translate("WaveDataDialog", "whv"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.whvTab), _translate("WaveDataDialog", "Selected Bin Depth"))
        self.label.setText(_translate("WaveDataDialog", "wr0, wr1, wr2, wr3, wzr"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wr0Tab), _translate("WaveDataDialog", "Range"))
        self.label_13.setText(_translate("WaveDataDialog", "wah"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wahTab), _translate("WaveDataDialog", "Average Range"))
        self.label_17.setText(_translate("WaveDataDialog", "whs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.whsTab), _translate("WaveDataDialog", "Selected Range"))
        self.label_6.setText(_translate("WaveDataDialog", "wts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wtsTab), _translate("WaveDataDialog", "Water Temp"))
        self.label_5.setText(_translate("WaveDataDialog", "wb0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wb0Tab), _translate("WaveDataDialog", "Beam Velocity Beam 0"))
        self.label_4.setText(_translate("WaveDataDialog", "wb1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wb1Tab), _translate("WaveDataDialog", "Beam Velocity Beam 1"))
        self.label_3.setText(_translate("WaveDataDialog", "wb2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wb2Tab), _translate("WaveDataDialog", "Beam Velocity Beam 2"))
        self.label_2.setText(_translate("WaveDataDialog", "wb3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wb3Tab), _translate("WaveDataDialog", "Beam Velocity Beam 3"))
        self.label_7.setText(_translate("WaveDataDialog", "wz0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wz0Tab), _translate("WaveDataDialog", "Beam Velocity Vertical Beam"))
        self.label_8.setText(_translate("WaveDataDialog", "wus"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wusTab), _translate("WaveDataDialog", "East Velocity"))
        self.label_9.setText(_translate("WaveDataDialog", "wvs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wvsTab), _translate("WaveDataDialog", "North Velocity"))
        self.label_10.setText(_translate("WaveDataDialog", "wzs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wzsTab), _translate("WaveDataDialog", "Vertical Velocity"))
        self.label_12.setText(_translate("WaveDataDialog", "wps, wzp"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wpsTab), _translate("WaveDataDialog", "Pressure"))
        self.label_14.setText(_translate("WaveDataDialog", "whg"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.whgTab), _translate("WaveDataDialog", "Heading"))
        self.label_16.setText(_translate("WaveDataDialog", "wph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wphTab), _translate("WaveDataDialog", "Pitch"))
        self.label_15.setText(_translate("WaveDataDialog", "wrl"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wrlTab), _translate("WaveDataDialog", "Roll"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WaveDataDialog = QtWidgets.QDialog()
    ui = Ui_WaveDataDialog()
    ui.setupUi(WaveDataDialog)
    WaveDataDialog.show()
    sys.exit(app.exec_())

