# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup_view.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Setup(object):
    def setupUi(self, Setup):
        Setup.setObjectName("Setup")
        Setup.resize(404, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Setup.sizePolicy().hasHeightForWidth())
        Setup.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Setup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.numBurstEnsLabel = QtWidgets.QLabel(Setup)
        self.numBurstEnsLabel.setObjectName("numBurstEnsLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.numBurstEnsLabel)
        self.numBurstEnsSpinBox = QtWidgets.QSpinBox(Setup)
        self.numBurstEnsSpinBox.setMaximum(10000)
        self.numBurstEnsSpinBox.setObjectName("numBurstEnsSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.numBurstEnsSpinBox)
        self.storagePathLabel = QtWidgets.QLabel(Setup)
        self.storagePathLabel.setObjectName("storagePathLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.storagePathLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.storagePathLineEdit = QtWidgets.QLineEdit(Setup)
        self.storagePathLineEdit.setObjectName("storagePathLineEdit")
        self.horizontalLayout_2.addWidget(self.storagePathLineEdit)
        self.selectFolderPushButton = QtWidgets.QPushButton(Setup)
        self.selectFolderPushButton.setObjectName("selectFolderPushButton")
        self.horizontalLayout_2.addWidget(self.selectFolderPushButton)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.formLayout)
        self.groupBox = QtWidgets.QGroupBox(Setup)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.selectedBin1ComboBox = QtWidgets.QComboBox(self.groupBox)
        self.selectedBin1ComboBox.setObjectName("selectedBin1ComboBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.selectedBin1ComboBox)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.selectedBin2ComboBox = QtWidgets.QComboBox(self.groupBox)
        self.selectedBin2ComboBox.setObjectName("selectedBin2ComboBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.selectedBin2ComboBox)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.selectedBin3ComboBox = QtWidgets.QComboBox(self.groupBox)
        self.selectedBin3ComboBox.setObjectName("selectedBin3ComboBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.selectedBin3ComboBox)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.corelationThresholdDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.corelationThresholdDoubleSpinBox.setObjectName("corelationThresholdDoubleSpinBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.corelationThresholdDoubleSpinBox)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.heightSourceComboBox = QtWidgets.QComboBox(self.groupBox)
        self.heightSourceComboBox.setObjectName("heightSourceComboBox")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.heightSourceComboBox)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.pressureSensorHeightDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.pressureSensorHeightDoubleSpinBox.setObjectName("pressureSensorHeightDoubleSpinBox")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pressureSensorHeightDoubleSpinBox)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.pressureSensorOffsetDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.pressureSensorOffsetDoubleSpinBox.setObjectName("pressureSensorOffsetDoubleSpinBox")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pressureSensorOffsetDoubleSpinBox)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.latitudeDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.latitudeDoubleSpinBox.setObjectName("latitudeDoubleSpinBox")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.latitudeDoubleSpinBox)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.longitudeDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.longitudeDoubleSpinBox.setObjectName("longitudeDoubleSpinBox")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.longitudeDoubleSpinBox)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Setup)
        QtCore.QMetaObject.connectSlotsByName(Setup)

    def retranslateUi(self, Setup):
        _translate = QtCore.QCoreApplication.translate
        Setup.setWindowTitle(_translate("Setup", "MainWindow"))
        self.numBurstEnsLabel.setText(_translate("Setup", "Number of Ensembles in Burst"))
        self.storagePathLabel.setText(_translate("Setup", "Output Directory"))
        self.selectFolderPushButton.setText(_translate("Setup", "DIR"))
        self.groupBox.setTitle(_translate("Setup", "Wave Setup"))
        self.label.setText(_translate("Setup", "Selected Bin 1"))
        self.label_2.setText(_translate("Setup", "Selected Bin 2"))
        self.label_3.setText(_translate("Setup", "Selected Bin 3"))
        self.label_4.setText(_translate("Setup", "Corelation Threshold"))
        self.label_5.setText(_translate("Setup", "Height Source"))
        self.label_6.setText(_translate("Setup", "Pressure Sensor Height (m)"))
        self.label_7.setText(_translate("Setup", "Pressure Sensor Offset (m)"))
        self.label_8.setText(_translate("Setup", "Latitude"))
        self.label_9.setText(_translate("Setup", "Longitude"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Setup = QtWidgets.QWidget()
    ui = Ui_Setup()
    ui.setupUi(Setup)
    Setup.show()
    sys.exit(app.exec_())

