# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup_view.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Setup(object):
    def setupUi(self, Setup):
        Setup.setObjectName("Setup")
        Setup.resize(650, 766)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Setup.sizePolicy().hasHeightForWidth())
        Setup.setSizePolicy(sizePolicy)
        self.groupBox_3 = QtWidgets.QGroupBox(Setup)
        self.groupBox_3.setGeometry(QtCore.QRect(11, 11, 609, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(19, 19, 571, 61))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.numEnsLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.numEnsLabel.setObjectName("numEnsLabel")
        self.horizontalLayout_2.addWidget(self.numEnsLabel)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget_3)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(Setup)
        self.groupBox.setGeometry(QtCore.QRect(10, 110, 609, 271))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 515, 227))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.serialPortComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.serialPortComboBox.setObjectName("serialPortComboBox")
        self.horizontalLayout_3.addWidget(self.serialPortComboBox)
        self.scanSerialPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.scanSerialPushButton.setObjectName("scanSerialPushButton")
        self.horizontalLayout_3.addWidget(self.scanSerialPushButton)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_3)
        self.baudComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.baudComboBox.setObjectName("baudComboBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.baudComboBox)
        self.serialConnectPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.serialConnectPushButton.setObjectName("serialConnectPushButton")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.serialConnectPushButton)
        self.serialDisconnectPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.serialDisconnectPushButton.setObjectName("serialDisconnectPushButton")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.serialDisconnectPushButton)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.serialTextBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.serialTextBrowser.setObjectName("serialTextBrowser")
        self.verticalLayout_8.addWidget(self.serialTextBrowser)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cmdLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.cmdLineEdit.setObjectName("cmdLineEdit")
        self.horizontalLayout_4.addWidget(self.cmdLineEdit)
        self.sendCmdPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.sendCmdPushButton.setObjectName("sendCmdPushButton")
        self.horizontalLayout_4.addWidget(self.sendCmdPushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.startPingPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startPingPushButton.setObjectName("startPingPushButton")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.startPingPushButton)
        self.stopPingPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stopPingPushButton.setObjectName("stopPingPushButton")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.stopPingPushButton)
        self.breakPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.breakPushButton.setObjectName("breakPushButton")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.breakPushButton)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.groupBox_2 = QtWidgets.QGroupBox(Setup)
        self.groupBox_2.setGeometry(QtCore.QRect(11, 401, 609, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 281, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.numBurstEnsLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.numBurstEnsLabel.setObjectName("numBurstEnsLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.numBurstEnsLabel)
        self.numBurstEnsSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.numBurstEnsSpinBox.setObjectName("numBurstEnsSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.numBurstEnsSpinBox)
        self.storagePathLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.storagePathLabel.setObjectName("storagePathLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.storagePathLabel)
        self.storagePathLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.storagePathLineEdit.setObjectName("storagePathLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.storagePathLineEdit)

        self.retranslateUi(Setup)
        QtCore.QMetaObject.connectSlotsByName(Setup)

    def retranslateUi(self, Setup):
        _translate = QtCore.QCoreApplication.translate
        Setup.setWindowTitle(_translate("Setup", "MainWindow"))
        self.groupBox_3.setTitle(_translate("Setup", "Monitor"))
        self.numEnsLabel.setText(_translate("Setup", "Ensemble Count: "))
        self.label.setText(_translate("Setup", "23"))
        self.groupBox.setTitle(_translate("Setup", "Terminal"))
        self.scanSerialPushButton.setText(_translate("Setup", "SCAN"))
        self.serialConnectPushButton.setText(_translate("Setup", "CONNECT"))
        self.serialDisconnectPushButton.setText(_translate("Setup", "DISCONNECT"))
        self.sendCmdPushButton.setText(_translate("Setup", "SEND"))
        self.startPingPushButton.setText(_translate("Setup", "START PING"))
        self.stopPingPushButton.setText(_translate("Setup", "STOP PING"))
        self.breakPushButton.setText(_translate("Setup", "BREAK"))
        self.groupBox_2.setTitle(_translate("Setup", "Setup"))
        self.numBurstEnsLabel.setText(_translate("Setup", "Number of Ensembles in Burst"))
        self.storagePathLabel.setText(_translate("Setup", "Storage Path"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Setup = QtWidgets.QWidget()
    ui = Ui_Setup()
    ui.setupUi(Setup)
    Setup.show()
    sys.exit(app.exec_())

